# Generated by Django 2.2.2 on 2019-06-08 18:04

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
from django.db.migrations import RunPython
from swapi import swapi


def get_character_data(apps, schema_editor):
    Character = apps.get_model('characters', "Character")
    for people in swapi.get_all('people').iter():
        available_fields = Character._meta.get_fields()
        available_fields = [i.name for i in available_fields]
        character_data = {i: getattr(people, i, None) for i in available_fields}
        Character.objects.get_or_create(**character_data)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.CharField(max_length=255)),
                ('eye_color', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Hombre'), ('Female', 'Mujer'), ('unknown', 'Desconocido'), ('n/a', 'N/A')], max_length=255)),
                ('hair_color', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('mass', models.CharField(max_length=255)),
                ('skin_color', models.CharField(max_length=255)),
                ('homeworld', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
            },
        ),
        RunPython(get_character_data, RunPython.noop)
    ]
