# Generated by Django 2.2.2 on 2019-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='films/default/default.jpg', upload_to='films/uploaded'),
        ),
    ]
